// <auto-generated />
using System;
using Fintrack.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fintrack.Infrastructure.Migrations
{
    [DbContext(typeof(FintrackContext))]
    partial class FintrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fintrack.Domain.Entities.FinancialOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("FinancialOperations");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.JwtRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.Mcc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mccs");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsExpense")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.TransactionTypeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsExpense")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypeTemplates");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MonobankAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MccTransactionType", b =>
                {
                    b.Property<Guid>("MccsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionTypesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MccsId", "TransactionTypesId");

                    b.HasIndex("TransactionTypesId");

                    b.ToTable("MccTransactionType");
                });

            modelBuilder.Entity("MccTransactionTypeTemplate", b =>
                {
                    b.Property<Guid>("MccsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionTypeTemplatesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MccsId", "TransactionTypeTemplatesId");

                    b.HasIndex("TransactionTypeTemplatesId");

                    b.ToTable("MccTransactionTypeTemplate");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.FinancialOperation", b =>
                {
                    b.HasOne("Fintrack.Domain.Entities.TransactionType", "TransactionType")
                        .WithMany("FinancialOperations")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fintrack.Domain.Entities.User", "User")
                        .WithMany("FinancialOperations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.JwtRefreshToken", b =>
                {
                    b.HasOne("Fintrack.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Fintrack.Domain.Entities.JwtRefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.TransactionType", b =>
                {
                    b.HasOne("Fintrack.Domain.Entities.User", "User")
                        .WithMany("TransactionTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MccTransactionType", b =>
                {
                    b.HasOne("Fintrack.Domain.Entities.Mcc", null)
                        .WithMany()
                        .HasForeignKey("MccsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fintrack.Domain.Entities.TransactionType", null)
                        .WithMany()
                        .HasForeignKey("TransactionTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MccTransactionTypeTemplate", b =>
                {
                    b.HasOne("Fintrack.Domain.Entities.Mcc", null)
                        .WithMany()
                        .HasForeignKey("MccsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fintrack.Domain.Entities.TransactionTypeTemplate", null)
                        .WithMany()
                        .HasForeignKey("TransactionTypeTemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.TransactionType", b =>
                {
                    b.Navigation("FinancialOperations");
                });

            modelBuilder.Entity("Fintrack.Domain.Entities.User", b =>
                {
                    b.Navigation("FinancialOperations");

                    b.Navigation("TransactionTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
